# ofenton Base
FROM ofenton/base:latest

MAINTAINER ofenton

# Install everything
RUN yum -y install \
    java-1.8.0-openjdk.x86_64;
    yum -y clean all

ENV DOCKER_CONTAINER='java_base'

# Finished
CMD ["Docker Java base container deploy complete"]
